################################################################################
#  _____  _                       _ _
# |  __ \(_)                     | | |
# | |  | |_ ___  ___ ___  _ __ __| | |     ___   __ _  __ _  ___ _ __
# | |  | | / __|/ __/ _ \| '__/ _` | |    / _ \ / _` |/ _` |/ _ \ '__|
# | |__| | \__ \ (_| (_) | | | (_| | |___| (_) | (_| | (_| |  __/ |
# |_____/|_|___/\___\___/|_|  \__,_|______\___/ \__, |\__, |\___|_|
#                                             __/ | __/ |
#                                            |___/ |___/
################################################################################
# ░ DISCORD LOGGER - CONFIGURATION FILE ░
# 📘 GitHub: https://github.com/LVCHLANN/DiscordLogger
# 📄 Documentation: https://github.com/LVCHLANN/DiscordLogger/tree/main/docs
################################################################################

# Discord Webhook URL to send logs to
discord-webhook-url: "INSERT-WEBHOOK-URL"

# Optional: Name of your server for networks using BungeeCord/Velocity (Remove the comment [#] to use)
# Helps label which server the event came from in multi-server setups
# server-name: "MyServerName"

log:
  player:
    join: true                  # Log when a player joins the server
    quit: true                  # Log when a player leaves the server
    chat: true                  # Log player chat messages
    death: true                 # Log player deaths
    advancement: false          # Log player advancements/achievements (placeholder)
    xp-change: false            # Log player XP gain or loss
    teleport: false             # Log player teleport events
    drop-item: false            # Log when a player drops an item
    pickup-item: false          # Log when a player picks up an item
    interact: false             # Log player interactions with blocks/entities
    respawn: false              # Log player respawns
    gamemode-change: false      # Log player gamemode changes
    damage: false               # Log player damage taken

  block:
    break: true                 # Log blocks broken by players
    place: true                 # Log blocks placed by players

  inventory:
    open: false                 # Log inventory opens (e.g., chests)
    click: false                # Log clicks inside inventories
    close: false                # Log inventory closes
    drag: false                 # Log item drags in inventory

  server:
    command: true               # Log server/console commands executed

  staff:
    executed-command: false     # Log any command executed by players (parsed)
    banned-player: false        # Log when a player is banned via /ban
    kicked-player: false        # Log when a player is kicked and by whom
    muted-player: false         # Log when a player is muted via /mute
    unmuted-player: false       # Log when a player is unmuted via /unmute
    warned-player: false        # Log when a player is warned via /warn
    changed-permissions: false  # Log permission changes (placeholder only)
    opped-player: false         # Log when OP is granted via /op
    deopped-player: false       # Log when OP is removed via /deop
    teleport-other: false       # Log when staff teleport others via /tp or /teleport
    cleared-inventory: false    # Log when inventories are cleared via /clear
    given-items: false          # Log when items are given via /give
    set-gamemode-other: false   # Log when gamemode is changed for others

debug:
  listener-register: false      # Log event listener registrations (for debugging)
  config-load: false            # Log config file loading (for debugging)
