name: DiscordLogger
main: com.DiscordLogger.Main
version: 1.1-ALPHA
api-version: 1.21
description: A plugin that logs events to Discord.
commands:
  discordlogger:
    description: Main command for DiscordLogger
    usage: /discordlogger reload
    permission: discordlogger.reload
    permission-message: You do not have permission to execute this command.