name: DiscordLogger
version: 1.1-ALPHA
main: com.DiscordLogger.Main
api-version: 1.21
authors:
  - "Lachlan Scott"
description: |
  A plugin to log Minecraft events and send them to a Discord webhook.

commands:
  discordlogger:
    description: Reloads the plugin and config.yml file
    usage: /discordlogger reload
    aliases: [dlreload]
    permission: discordlogger.reload  # Add this line for permission

permissions:
  discordlogger.reload:
    description: "Allows the user to trigger the /discordlogger reload command"
    default: op

