name: DiscordLogger
version: 1.0
main: com.DiscordLogger.Main
api-version: 1.21
authors:
  - "Lachlan Scott"
description: |
  A plugin to log Minecraft events and send them to a Discord webhook.

commands:
  reload:
    description: Reloads the plugin and config.yml file
    usage: /discordlogger reload

permissions:
  discordlogger.use:
    description: "Allows the user to trigger the /discordlogger reload command"
    default: op
